"""user phone change audit

Revision ID: b046276164da
Revises: 1daf2b084378
Create Date: 2026-09-09 23:31:50.602301
"""
from alembic import op
import sqlalchemy as sa


revision = 'b046276164da'
down_revision = '1daf2b084378'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_phone_change',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('previous_phone', sa.String(length=32), nullable=True),
    sa.Column('new_phone', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_user_phone_change_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_phone_change'))
    )
    op.create_index(op.f('ix_user_phone_change_user_id'), 'user_phone_change', ['user_id'], unique=False)

    # RLS is not inherited. The migration that enabled it hardcodes a table
    # list, so every new table must turn it on explicitly or it silently ships
    # unprotected. TestRowLevelSecurity fails if this is forgotten.
    op.execute('ALTER TABLE "user_phone_change" ENABLE ROW LEVEL SECURITY')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE "user_phone_change" DISABLE ROW LEVEL SECURITY')
    op.drop_index(op.f('ix_user_phone_change_user_id'), table_name='user_phone_change')
    op.drop_table('user_phone_change')
    # ### end Alembic commands ###
