"""core schema

Revision ID: fb76533e5c83
Revises: 
Create Date: 2026-09-02 10:03:11.385814
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'fb76533e5c83'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country_pack',
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('locale', sa.String(length=16), nullable=False),
    sa.Column('tax_accounts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('disclaimer_version', sa.String(length=32), nullable=True),
    sa.Column('is_launched', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_country_pack')),
    sa.UniqueConstraint('country_code', name=op.f('uq_country_pack_country_code'))
    )
    op.create_table('disclaimer_version',
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_disclaimer_version'))
    )
    op.create_index('uq_disclaimer_country_version', 'disclaimer_version', ['country_code', 'version'], unique=True)
    op.create_table('feature_availability',
    sa.Column('feature_key', sa.String(length=64), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('plan', sa.Enum('free', 'personal', 'family', name='plan_tier'), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feature_availability'))
    )
    op.create_index(op.f('ix_feature_availability_feature_key'), 'feature_availability', ['feature_key'], unique=False)
    op.create_index('uq_feature_scope', 'feature_availability', ['feature_key', 'country_code', 'plan'], unique=True)
    op.create_table('household',
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_household'))
    )
    op.create_index(op.f('ix_household_country_code'), 'household', ['country_code'], unique=False)
    op.create_table('account',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.Enum('chequing', 'savings', 'credit_card', 'loan', 'investment', 'cash', name='account_kind'), nullable=False),
    sa.Column('institution', sa.String(length=255), nullable=True),
    sa.Column('account_number_last4', sa.String(length=4), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('external_account_id', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], name=op.f('fk_account_household_id_household'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_account'))
    )
    op.create_index(op.f('ix_account_household_id'), 'account', ['household_id'], unique=False)
    op.create_table('budget',
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('is_user_modified', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], name=op.f('fk_budget_household_id_household'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_budget'))
    )
    op.create_index(op.f('ix_budget_household_id'), 'budget', ['household_id'], unique=False)
    op.create_index('uq_budget_household_period', 'budget', ['household_id', 'period_start'], unique=True)
    op.create_table('category',
    sa.Column('household_id', sa.UUID(), nullable=True),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], name=op.f('fk_category_household_id_household'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['category.id'], name=op.f('fk_category_parent_id_category'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_category'))
    )
    op.create_index(op.f('ix_category_household_id'), 'category', ['household_id'], unique=False)
    op.create_index('uq_category_household_slug', 'category', ['household_id', 'slug'], unique=True)
    op.create_table('chat_conversation',
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('messages', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_message_preview', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], name=op.f('fk_chat_conversation_household_id_household'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_conversation'))
    )
    op.create_index(op.f('ix_chat_conversation_household_id'), 'chat_conversation', ['household_id'], unique=False)
    op.create_table('document_upload',
    sa.Column('storage_path', sa.String(length=1024), nullable=True),
    sa.Column('original_filename', sa.String(length=512), nullable=True),
    sa.Column('content_type', sa.String(length=128), nullable=True),
    sa.Column('byte_size', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('queued', 'processing', 'awaiting_review', 'completed', 'failed', name='document_status'), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('extracted_count', sa.Integer(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], name=op.f('fk_document_upload_household_id_household'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_upload'))
    )
    op.create_index(op.f('ix_document_upload_household_id'), 'document_upload', ['household_id'], unique=False)
    op.create_index(op.f('ix_document_upload_status'), 'document_upload', ['status'], unique=False)
    op.create_table('goal',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('horizon', sa.Enum('short_term', 'long_term', name='goal_horizon'), nullable=False),
    sa.Column('target_minor_units', sa.BigInteger(), nullable=False),
    sa.Column('saved_minor_units', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('achieved_at', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], name=op.f('fk_goal_household_id_household'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_goal'))
    )
    op.create_index(op.f('ix_goal_household_id'), 'goal', ['household_id'], unique=False)
    op.create_table('health_score_snapshot',
    sa.Column('scored_on', sa.Date(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('formula_version', sa.String(length=32), nullable=False),
    sa.Column('components', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], name=op.f('fk_health_score_snapshot_household_id_household'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_health_score_snapshot'))
    )
    op.create_index(op.f('ix_health_score_snapshot_household_id'), 'health_score_snapshot', ['household_id'], unique=False)
    op.create_index('uq_health_score_household_date', 'health_score_snapshot', ['household_id', 'scored_on'], unique=True)
    op.create_table('subscription_entitlement',
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('plan', sa.Enum('free', 'personal', 'family', name='plan_tier'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('external_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], name=op.f('fk_subscription_entitlement_household_id_household'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscription_entitlement'))
    )
    op.create_index('ix_entitlement_household_active', 'subscription_entitlement', ['household_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_subscription_entitlement_household_id'), 'subscription_entitlement', ['household_id'], unique=False)
    op.create_table('user',
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('auth_user_id', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], name=op.f('fk_user_household_id_household'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('auth_user_id', name=op.f('uq_user_auth_user_id')),
    sa.UniqueConstraint('phone', name=op.f('uq_user_phone'))
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=False)
    op.create_index(op.f('ix_user_household_id'), 'user', ['household_id'], unique=False)
    op.create_table('budget_line',
    sa.Column('budget_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('allocated_minor_units', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['budget_id'], ['budget.id'], name=op.f('fk_budget_line_budget_id_budget'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name=op.f('fk_budget_line_category_id_category'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_budget_line'))
    )
    op.create_index('uq_budget_line_budget_category', 'budget_line', ['budget_id', 'category_id'], unique=True)
    op.create_table('debt',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=True),
    sa.Column('balance_minor_units', sa.BigInteger(), nullable=False),
    sa.Column('minimum_payment_minor_units', sa.BigInteger(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('interest_rate_bps', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], name=op.f('fk_debt_account_id_account'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], name=op.f('fk_debt_household_id_household'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_debt'))
    )
    op.create_index(op.f('ix_debt_household_id'), 'debt', ['household_id'], unique=False)
    op.create_table('transaction',
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('document_upload_id', sa.UUID(), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('occurred_on', sa.Date(), nullable=False),
    sa.Column('amount_minor_units', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('direction', sa.Enum('debit', 'credit', name='transaction_direction'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('normalized_description', sa.String(length=512), nullable=False),
    sa.Column('merchant', sa.String(length=255), nullable=True),
    sa.Column('source', sa.Enum('upload', 'manual', 'aggregator', name='transaction_source'), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('extraction_confidence', sa.Integer(), nullable=True),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], name=op.f('fk_transaction_account_id_account'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name=op.f('fk_transaction_category_id_category'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_upload_id'], ['document_upload.id'], name=op.f('fk_transaction_document_upload_id_document_upload'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], name=op.f('fk_transaction_household_id_household'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transaction'))
    )
    op.create_index(op.f('ix_transaction_household_id'), 'transaction', ['household_id'], unique=False)
    op.create_index('ix_transaction_household_occurred', 'transaction', ['household_id', 'occurred_on'], unique=False)
    op.create_index(op.f('ix_transaction_merchant'), 'transaction', ['merchant'], unique=False)
    op.create_index(op.f('ix_transaction_needs_review'), 'transaction', ['needs_review'], unique=False)
    op.create_index('uq_transaction_dedup', 'transaction', ['account_id', 'occurred_on', 'amount_minor_units', 'normalized_description'], unique=True)
    op.create_table('user_identity',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.Enum('phone', 'google', 'apple', name='auth_provider'), nullable=False),
    sa.Column('provider_user_id', sa.String(length=255), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_user_identity_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_identity')),
    sa.UniqueConstraint('provider', 'provider_user_id', name='provider_identity')
    )
    op.create_index(op.f('ix_user_identity_user_id'), 'user_identity', ['user_id'], unique=False)
    op.create_table('category_correction',
    sa.Column('transaction_id', sa.UUID(), nullable=True),
    sa.Column('merchant_pattern', sa.String(length=255), nullable=False),
    sa.Column('predicted_category_id', sa.UUID(), nullable=True),
    sa.Column('corrected_category_id', sa.UUID(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['corrected_category_id'], ['category.id'], name=op.f('fk_category_correction_corrected_category_id_category'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], name=op.f('fk_category_correction_household_id_household'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['predicted_category_id'], ['category.id'], name=op.f('fk_category_correction_predicted_category_id_category'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transaction.id'], name=op.f('fk_category_correction_transaction_id_transaction'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_category_correction'))
    )
    op.create_index(op.f('ix_category_correction_household_id'), 'category_correction', ['household_id'], unique=False)
    op.create_index(op.f('ix_category_correction_merchant_pattern'), 'category_correction', ['merchant_pattern'], unique=False)

    # Currency length checks. Declared at table level in the models because a
    # CheckConstraint passed to mapped_column is silently discarded — the
    # autogenerated migration had none, and a 2-letter country code inserted
    # where a currency belongs was accepted.
    for _table in (
        "account",
        "transaction",
        "budget",
        "budget_line",
        "goal",
        "debt",
        "country_pack",
    ):
        op.create_check_constraint(
            "currency_iso4217_length", _table, "char_length(currency) = 3"
        )
    # ### end Alembic commands ###



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_category_correction_merchant_pattern'), table_name='category_correction')
    op.drop_index(op.f('ix_category_correction_household_id'), table_name='category_correction')
    op.drop_table('category_correction')
    op.drop_index(op.f('ix_user_identity_user_id'), table_name='user_identity')
    op.drop_table('user_identity')
    op.drop_index('uq_transaction_dedup', table_name='transaction')
    op.drop_index(op.f('ix_transaction_needs_review'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_merchant'), table_name='transaction')
    op.drop_index('ix_transaction_household_occurred', table_name='transaction')
    op.drop_index(op.f('ix_transaction_household_id'), table_name='transaction')
    op.drop_table('transaction')
    op.drop_index(op.f('ix_debt_household_id'), table_name='debt')
    op.drop_table('debt')
    op.drop_index('uq_budget_line_budget_category', table_name='budget_line')
    op.drop_table('budget_line')
    op.drop_index(op.f('ix_user_household_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_subscription_entitlement_household_id'), table_name='subscription_entitlement')
    op.drop_index('ix_entitlement_household_active', table_name='subscription_entitlement')
    op.drop_table('subscription_entitlement')
    op.drop_index('uq_health_score_household_date', table_name='health_score_snapshot')
    op.drop_index(op.f('ix_health_score_snapshot_household_id'), table_name='health_score_snapshot')
    op.drop_table('health_score_snapshot')
    op.drop_index(op.f('ix_goal_household_id'), table_name='goal')
    op.drop_table('goal')
    op.drop_index(op.f('ix_document_upload_status'), table_name='document_upload')
    op.drop_index(op.f('ix_document_upload_household_id'), table_name='document_upload')
    op.drop_table('document_upload')
    op.drop_index(op.f('ix_chat_conversation_household_id'), table_name='chat_conversation')
    op.drop_table('chat_conversation')
    op.drop_index('uq_category_household_slug', table_name='category')
    op.drop_index(op.f('ix_category_household_id'), table_name='category')
    op.drop_table('category')
    op.drop_index('uq_budget_household_period', table_name='budget')
    op.drop_index(op.f('ix_budget_household_id'), table_name='budget')
    op.drop_table('budget')
    op.drop_index(op.f('ix_account_household_id'), table_name='account')
    op.drop_table('account')
    op.drop_index(op.f('ix_household_country_code'), table_name='household')
    op.drop_table('household')
    op.drop_index('uq_feature_scope', table_name='feature_availability')
    op.drop_index(op.f('ix_feature_availability_feature_key'), table_name='feature_availability')
    op.drop_table('feature_availability')
    op.drop_index('uq_disclaimer_country_version', table_name='disclaimer_version')
    op.drop_table('disclaimer_version')
    op.drop_table('country_pack')

    # Postgres enum types are created implicitly alongside the tables that use
    # them, but drop_table does NOT remove them. Without this, `downgrade base`
    # leaves all seven behind and the next `upgrade head` fails with
    # "type ... already exists" — which is exactly when downgrade is needed.
    for enum_type in (
        "auth_provider",
        "transaction_source",
        "transaction_direction",
        "goal_horizon",
        "document_status",
        "account_kind",
        "plan_tier",
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum_type}")
    # ### end Alembic commands ###
