#!/usr/bin/env bash
# Prove every migration applies, reverses and re-applies (ticket #15).
#
# CI runs this against a throwaway Postgres service container. To rehearse
# locally with the same image:
#
#   docker run -d --name finai-pg -e POSTGRES_PASSWORD=postgres -p 55432:5432 \
#     ghcr.io/pgmq/pg17-pgmq:v1.5.1
#   DATABASE_URL=postgresql://postgres:postgres@localhost:55432/postgres \
#     PG_CONTAINER=finai-pg PYTHON=.venv/bin/python scripts/check_migrations.sh
#   docker rm -f finai-pg
#
# DESTRUCTIVE: it downgrades to base, which drops every table. A developer's
# .env points at PRODUCTION, so this refuses to run unless both the runtime and
# the migration DSN — as the app's own settings resolve them, .env included —
# point at localhost.
#
# What it proves is migration CORRECTNESS on Postgres 17. It does not prove the
# migrations survive Supabase's transaction pooler; see the database job in
# .github/workflows/ci.yml.
set -euo pipefail

: "${DATABASE_URL:?set DATABASE_URL to the throwaway database}"
: "${PG_CONTAINER:?set PG_CONTAINER to the Postgres container name or id}"

# Alembic uses migration_dsn, which prefers MIGRATION_DATABASE_URL — and a
# developer's .env sets that to the production session pooler. Exporting
# DATABASE_URL alone would still migrate production, so pin both explicitly.
export MIGRATION_DATABASE_URL="$DATABASE_URL"

PYTHON="${PYTHON:-python}"
ALEMBIC=("$PYTHON" -m alembic)
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

step() { printf '\n==> %s\n' "$*"; }
fail() {
  printf '\nFAIL: %s\n' "$*" >&2
  exit 1
}

step "Refusing any database that is not on localhost"
# Resolved through Settings rather than by parsing the variable: the question
# is which database the app and Alembic will actually connect to.
target="$("$PYTHON" - <<'PY'
import sys

from sqlalchemy.engine import make_url

from app.config import get_settings

settings = get_settings()
local = {"localhost", "127.0.0.1", "::1"}
for label, dsn in (("runtime", settings.database_dsn), ("migration", settings.migration_dsn)):
    host = make_url(dsn).host
    if host not in local:
        sys.exit(f"{label} DSN points at {host!r}, not localhost — refusing to drop its tables")
url = make_url(settings.migration_dsn)
print(url.username, url.database)
PY
)"
read -r DB_USER DB_NAME <<<"$target"
echo "ok: runtime and migration DSNs are both local (user=$DB_USER, db=$DB_NAME)"

psql_c() {
  docker exec -i "$PG_CONTAINER" psql -U "$DB_USER" -d "$DB_NAME" -tAX -v ON_ERROR_STOP=1 -c "$1"
}

# pg_dump runs inside the container, so the runner's own client version cannot
# disagree with the server. Patched pg_dump (17.6+) brackets its output with
# \restrict / \unrestrict lines carrying a random key — strip them, or two
# dumps of an identical schema would never compare equal.
dump_schema() {
  docker exec "$PG_CONTAINER" pg_dump --schema-only --no-owner --no-privileges \
    -U "$DB_USER" -d "$DB_NAME" | sed -e '/^\\restrict /d' -e '/^\\unrestrict /d'
}

current() { "${ALEMBIC[@]}" current 2>/dev/null; }

queue_count() {
  psql_c "SELECT count(*) FROM pgmq.list_queues() WHERE queue_name = 'extraction_jobs'"
}

# Everything a downgrade could leave behind in the application schema. The
# enum types are here on purpose: an autogenerated downgrade() once dropped the
# tables but left seven enum types in place (ticket #10).
LEFTOVERS_SQL="
SELECT kind || ' ' || name FROM (
  SELECT 'table' AS kind, tablename AS name FROM pg_tables
    WHERE schemaname = 'public' AND tablename <> 'alembic_version'
  UNION ALL SELECT 'enum', t.typname FROM pg_type t
    JOIN pg_namespace n ON n.oid = t.typnamespace
    WHERE n.nspname = 'public' AND t.typtype = 'e'
  UNION ALL SELECT 'sequence', sequencename FROM pg_sequences WHERE schemaname = 'public'
  UNION ALL SELECT 'view', viewname FROM pg_views WHERE schemaname = 'public'
  UNION ALL SELECT 'function', p.proname FROM pg_proc p
    JOIN pg_namespace n ON n.oid = p.pronamespace WHERE n.nspname = 'public'
) leftovers ORDER BY 1"

step "Starting from an empty database"
[ -z "$(psql_c "$LEFTOVERS_SQL")" ] || fail "the database is not empty — start from a fresh container"

step "Enabling pgmq, as production has it"
# The image makes pgmq available; this makes it installed. The queue migration
# checks pg_extension, so without this its real path would be skipped here.
psql_c "CREATE EXTENSION IF NOT EXISTS pgmq" >/dev/null ||
  fail "this image does not provide pgmq — the queue migration's real path would go untested"

step "Exactly one migration head"
heads="$("${ALEMBIC[@]}" heads 2>&1)"
count="$(grep -c '(head)' <<<"$heads" || true)"
[ "$count" -eq 1 ] || fail "expected one head, found $count — two migrations share a parent, which is a merge-order bug:
$heads"
echo "ok: $heads"

step "upgrade head — every migration applies to an empty database"
"${ALEMBIC[@]}" upgrade head
first="$(current)"
dump_schema >"$WORK/first.sql"
[ "$(queue_count)" = "1" ] || fail "no extraction_jobs queue after upgrade — the guarded create did not run"
echo "ok: at $first, queue created"

step "upgrade head again — a no-op the second time"
"${ALEMBIC[@]}" upgrade head
[ "$(current)" = "$first" ] || fail "the second upgrade moved the revision: $(current)"
dump_schema >"$WORK/again.sql"
diff -u "$WORK/first.sql" "$WORK/again.sql" || fail "the second upgrade changed the schema"
echo "ok: revision and schema unchanged"

step "downgrade base — every downgrade() runs, and leaves nothing behind"
"${ALEMBIC[@]}" downgrade base
leftovers="$(psql_c "$LEFTOVERS_SQL")"
[ -z "$leftovers" ] || fail "downgrade base left objects behind:
$leftovers"
# Kept deliberately: dropping the queue would destroy in-flight uploads.
[ "$(queue_count)" = "1" ] || fail "the queue did not survive downgrade — its downgrade() is meant to be a no-op"
echo "ok: schema empty, queue kept by design"

step "upgrade head once more — the round trip reproduces the schema exactly"
# This is also where the queue migration meets an existing queue, which is the
# guard production depends on.
"${ALEMBIC[@]}" upgrade head
dump_schema >"$WORK/second.sql"
diff -u "$WORK/first.sql" "$WORK/second.sql" ||
  fail "the round trip changed the schema — some downgrade() does not exactly undo its upgrade()"
[ "$(queue_count)" = "1" ] || fail "the queue guard created a duplicate or failed on re-apply"
echo "ok: identical schema, one queue"

printf '\nAll migration checks passed in %ss.\n' "$SECONDS"
