#!/usr/bin/env python3
"""Reference implementation of ticket 3.2's on-device redactor.

The real one runs in `sharedLogic` on the phone. This exists so the fixture in
`tests/fixtures/` is generated by the rules rather than hand-edited, and so the
mobile implementation has something to agree with line for line.

The rules, from FinAI-Mobile-2026#29:
  * a run of 7+ digits (spaces and dashes ignored) keeps only its last 4
  * a line carrying an email address, a phone number or a Canadian postal code
    is dropped whole
  * on page 1, every line above the first transaction-like line is dropped —
    that block holds the name and address

Note what the third rule also removes: the statement period, and with it the
only place the year appears. That is why the period is sent as a field instead
(PRD F2, 2026-09-21) — not as something to scrape back out of the text.
"""

from __future__ import annotations

import re
import sys

DIGIT_RUN = re.compile(r"(?:\d[ -]?){7,}\d*")
EMAIL = re.compile(r"[\w.+-]+@[\w-]+\.[\w.]+")
PHONE = re.compile(r"\b(?:\+?1[ -]?)?(?:\(\d{3}\)|\d{3})[ -]\d{3}[ -]\d{4}\b")
# The trailing \b matters: without it this also eats "SPOTIFY P3A4B5C6", which
# is a transaction, not an address. Over-redaction fails the feature just as
# surely as under-redaction.
POSTAL = re.compile(r"\b[A-Z]\d[A-Z][ -]?\d[A-Z]\d\b")
AMOUNT = re.compile(r"\d[\d,]*\.\d{2}")
# `\s?`, not `\s*`: a date is "14 Aug" or "Aug 14", never a word and a number
# separated by a column of spaces. With `\s*` this reads "Opening balance
#     2,184.63" as a dated amount, and the header cut lands in the wrong place.
DATE = re.compile(
    r"\b(\d{1,2}[/-]\d{1,2}|\d{1,2}\s?[A-Za-z]{3,}|[A-Za-z]{3,}\s?\d{1,2})\b"
)


def _mask(match: re.Match[str]) -> str:
    digits = re.sub(r"[ -]", "", match.group(0))
    return "•" * 4 + digits[-4:]


def looks_like_a_transaction(line: str) -> bool:
    return bool(AMOUNT.search(line) and DATE.search(line))


def redact(text: str) -> str:
    lines = text.splitlines()
    first = next(
        (i for i, line in enumerate(lines) if looks_like_a_transaction(line)), 0
    )
    kept = []
    for line in lines[first:]:
        if EMAIL.search(line) or PHONE.search(line) or POSTAL.search(line):
            continue
        kept.append(DIGIT_RUN.sub(_mask, line))
    return "\n".join(kept).strip() + "\n"


if __name__ == "__main__":
    sys.stdout.write(redact(sys.stdin.read()))
